- source/tutorial/authenticate-with-java-driver.txt
https://jira.mongodb.org/browse/JAVA-869
Moved 3.0 syntax to it's own tutorial (#248)
> Fix typo in MongoCredential and correct how to specify SSL in Java Driver < 3.0

- source/drivers/cpp.txt
- source/drivers/csharp.txt
- source/drivers/driver-compatibility-reference.txt
- source/drivers/java.txt
- source/drivers/node-js.txt
- source/drivers/perl.txt
- source/drivers/php.txt
- source/drivers/python.txt
- source/drivers/scala.txt
- 3.4 driver compat: C, Cxx, Node, Java, Csharp
- 3.4 driver compat: perl
- 3.4 driver compat: php
- 3.4 driver compat: python
- 3.4 driver compat: motor
- 3.4 driver compat: ruby
- 3.4 driver compat: scala
- 3.4: driver compat cleanup
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/allison/master/drivers/driver-compatibility-reference.html
> 3.4 driver compat diagram updates

- source/drivers/csharp.txt
- source/drivers/driver-compatibility-reference.txt
Staged at https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/robertjustice/DOCS-11023/drivers/csharp.html.
> Updated C#/.NET compatibility tables. (DOCS-11023)

- source/drivers/php-libraries.txt
Adds a dedicated symfony bundle to the list : drivers/php-libraries.txt
https://github.com/facile-it/mongodb-bundle
> New entry for symfony in drivers/php-libraries.txt

- source/drivers/driver-compatibility-reference.txt
- source/drivers/perl.txt
This makes three changes:
* Shows that no available version of the driver is recommended for 3.6.
* Shows that only 1.8.x supports Perl 5.26
* Removes an extraneous link from the Perl page to the all-drivers
compat page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/430)
> Update Perl compatibility tables

- source/drivers/php.txt
Add MongoDB 3.6 and PHP 7.2 to compat tables, update tables for PHPC 1.4 and PHPLIB 1.3, and drop HHVM and mongo-1.5 from all tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/431)
> Update server and language compat tables

- source/drivers/php-libraries.txt
https://github.com/mongodb/docs-ecosystem/commit/9e3c3e4ac08666637efcbcca25c3ea4b8fa89e77 originally added this project with incorrect indentation. @kay-kim attempted to fix it in https://github.com/mongodb/docs-ecosystem/commit/187dae9bca66a2bbc34e21b11d64dcb82da7d6c3#diff-8fb17b84ed41ac74a7db675e4f9b8001R63 but that left the bullet entry in a blockquote (see: https://docs.mongodb.com/ecosystem/drivers/php-libraries/#framework-integrations).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/433)
> Fix indentation for facile-it/mongodb-bundle and reword

- source/drivers/community-supported-drivers.txt
- source/drivers/driver-compatibility-reference.txt
- source/drivers/scala.txt
Removed the community section of Scala as it was out of date.
Removed MongoDB 2.4 from the Scala driver matrix.
DOCS-11359 DOCS-11352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/435)
> Fixed compatibility for Casbah

- source/drivers/php.txt
- source/includes/extracts-driver-compatibility-matrix.yaml
We recently had a question from a support associate about PHPLIB language compatibility. This should address that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/441)
> Use consistent labels for PHP server/language compat tables

- source/drivers/driver-compatibility-reference.txt
- source/includes/php-mongodb-compatibility-table.rst
libmongoc dropped support for 2.6 in 1.10 (CDRIVER-2510), which is included in PHPC 1.5.
See: https://jira.mongodb.org/browse/CDRIVER-2510
/cc @derickr @ajdavis
> Update server compat tables for C and PHP

- source/use-cases/storing-log-data.txt
Staging link: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/danielborowski/DOCSP-3269/use-cases/storing-log-data.html
> (DOCSP-3269) add quotes to python keys

- source/drivers/driver-compatibility-reference.txt
- source/drivers/go.txt
- source/includes/language-compatibility-table-go.rst
- source/includes/mongodb-compatibility-table-go.rst
This also adds a connection example for Atlas.
https://jira.mongodb.org/browse/DOCSP-4584
https://jira.mongodb.org/browse/DOCSP-5402
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/go-driver-landing/drivers/go.html
> DOCSP-5402 DOCSP-4584 Apply template to Go driver landing page

- source/drivers/perl.txt
This page inherited a bug from the Atlas console connection snippet.
This uses single quotes in the snippet so as not to interpolate
a variable.
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docs-12826-perl-snippet-fix/drivers/perl.html#connect-to-mongodb-atlas
> DOCS-12826 Fix perl connect to Atlas snippet

- source/drivers/driver-compatibility-reference.txt
Tables copied from https://docs.mongodb.com/ruby-driver/current/reference/driver-compatibility/
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docs-12791-ruby-version-table/drivers/driver-compatibility-reference.html#ruby-driver-compatibility
> DOCS-12791 Add Ruby 2.7 and 2.8 to compatibility table

- source/drivers/csharp.txt
- source/drivers/driver-compatibility-reference.txt
- source/drivers/java.txt
- source/drivers/node.txt
- source/drivers/pymongo.txt
- source/includes/mongodb-compatibility-table-csharp.rst
- source/includes/mongodb-compatibility-table-java.rst
- source/includes/mongodb-compatibility-table-node.rst
- source/includes/mongodb-compatibility-table-python.rst
This adds the availability table to the MongoDB compatibility
section of the following drivers: Node, C#, Python, and Java.
Please look at the Node, C#/.NET, Python, and Java landing pages
on the compatibility section:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5987-4.2-compat/drivers/node.html#mongodb-compatibility
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5987-4.2-compat/drivers/pymongo.html#mongodb-compatibility
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5987-4.2-compat/drivers/csharp.html#mongodb-compatibility
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5987-4.2-compat/drivers/java.html#mongodb-compatibility
Please also look at the Driver compatibility page sections for each
of …
> DOCSP-5987 Add 4.2 feature availability table

- source/includes/driver-table.rst
- Updates the links to outdated api.mongodb.com pages
- Ruby and Python still have up-to-date api.mongodb.com pages, so
I left those links alone.
- Updates the MongoDB University course links for Python, Java
and JS.
- Remove deprecated C# course link
https://jira.mongodb.org/browse/DOCS-12847
https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/bush/docs-12847-java-api-link/index.html
> DOCS-12847 Update links on Drivers index page

- source/includes/language-compatibility-table-csharp.rst
- source/includes/mongodb-compatibility-table-csharp.rst
- Adds 2.8 driver version compatibility
- Updates language compatibility table to include .NET Core 2.1, Core 2.2,
Framwork 4.7 and Framework 4.8.
https://jira.mongodb.org/browse/DOCS-11995
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docs-11995-csharp-compat/drivers/driver-compatibility-reference.html#c-net-driver-compatibility
and https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docs-11995-csharp-compat/drivers/csharp.html#language-compatibility (single source)
> DOCS-11995 Update C#/.NET compatibility table

- source/drivers/perl.txt
This adds a deprecation warnings to the Perl driver landing page.
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCS-12971/drivers/perl.html)
[JIRA](https://jira.mongodb.org/browse/DOCS-12971)
> Add deprecation warning for Perl driver

- source/includes/language-compatibility-table-php.rst
PHPC 1.6 and PHPLIB 1.5 officially support PHP 7.4 in its current state and will fully support it once released.
> Add PHP 7.4 to the PHP driver compatibility list

- source/drivers/cxx.txt
- source/includes/mongodb-compatibility-table-cxx.rst
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCS-12995/drivers/cxx.html#mongodb-compatibility)
This adds an admonition to the cxx page and marks the 3.5 version as in development.
> (DOCS-12995): add admonition for version in dev

- source/connectors/kafka-source.txt
JIRA: none
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/ccho-kafka-source-typo-fix/connectors/kafka-source.html
> Kafka Source Connector - fix typo "updatelookup" => "updateLookup"

- source/drivers.txt
- source/drivers/community-supported-drivers.txt
- source/drivers/swift.txt
- source/includes/driver-table.rst
- source/includes/language-compatibility-table-swift.rst
- source/includes/mongodb-compatibility-table-swift.rst
This adds a page for the Swift driver to ecosystem, noting that it is an alpha version. It also adds a language and mongodb compatibility table and removes the now deprecated Perfect-MongoDB driver from the list of community supported drivers. I did also check MongoKitten and it looks like it is actively developed so didn't remove it.
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6911/drivers/swift.html)
> (DOCSP-6911) - adds swift driver

- source/drivers/reactive-streams.txt
Fix for a warning caused by reference to a nonexistent file.
JIRA: none
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-2157-reactive-streams-page/drivers/java.html
> remove unused extract

- source/drivers/php.txt
Fixes https://github.com/mongodb/docs-ecosystem/commit/dd24fdb130917681cde5c45646a17bb3a48de18c#diff-90020279a86a94415c6f59c61c9125a3
> Escape slashes in class name

- conf.py
- source/drivers/specs.txt
JIRA: https://jira.mongodb.org/browse/DOCS-10899
Staging: https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/DOCS-10899-driver-specs-table-update/index.html
- Updated extlinks for specs
- Clarified MongoDB 2.6 and later
- Moved GridFS, SDAM, and Command Monitoring checkmarks to Core Driver column
- Removed mention of MONGODB-CR
- Consolidated and labeled non-enterprise and enterprise auth
- Updated several links to point directly to rst files rather than directory containing them on GitHub.
> DOCS-10899: update driver specs table

- source/driver-compatibility-reference.txt
- source/includes/language-compatibility-table-csharp.rst
https://jira.mongodb.org/browse/DOCSP-9809
https://docs-mongodbcom-staging.corp.mongodb.com/861ea72/drivers/docsworker/DOCSP-9809/driver-compatibility-reference
> (DOCSP-9809) - adds swift and rust compat

- source/includes/language-compatibility-table-python.rst
- source/includes/mongodb-compatibility-table-python.rst
https://jira.mongodb.org/browse/DOCS-13630
https://docs-mongodbcom-staging.corp.mongodb.com/954cf73/drivers/docsworker/DOCS-13630-python-compat-matrix/pymongo
> DOCS-13630: python compatibility matrix update for 3.10 and 3.11

- source/community-supported-drivers.txt
- source/drivers.txt
- source/includes/important-community-drivers.rst
https://jira.mongodb.org/browse/DOP-958
https://mongodb.invisionapp.com/share/PTVY7JNYUXZ#/screens/404664689
https://docs-mongodbcom-staging.corp.mongodb.com/8763975/drivers/docsworker-xlarge/DOP-958/community-supported-drivers
- We don't yet support striped tables on Docs (to the best of my knowledge), but I added `:class: striped` to the directive to support that styling when it is added.
- I checked all the links to ensure they're not dead
> DOP-958: Update community drivers page

- source/includes/language-compatibility-table-php.rst
- source/includes/php-mongodb-compatibility-table.rst
@akung0324 asked about this in Slack.
PHPC 1.7 and PHPLIB 1.6 were no different from the previous versions, respectively, aside from adding FLE support and I don't believe we track that information in this table.
cc: @alcaeus
> Update PHP compatibility tables

- source/go.txt
https://jira.mongodb.org/browse/DOCSP-10523
https://docs-mongodbcom-staging.corp.mongodb.com/0fc41ed/drivers/docsworker/DOCSP-10523-add-golang-tutorials/go/
> DOCSP-10523: add link to golang tutorials

- source/community-supported-drivers.txt
- Change template name from `landing` to `blank` in order to address changes introduced in [snooty@v0.4.12](https://github.com/mongodb/snooty/releases/tag/v0.4.12)
https://docs-mongodbcom-staging.corp.mongodb.com/934b109/drivers/docsworker-xlarge/rename-template/community-supported-drivers
> Rename Community Supported Drivers page template

- config/redirects
- source/includes/driver-table.rst
Additional fix for https://jira.mongodb.org/browse/DOCS-13677
https://docs-mongodbcom-staging.corp.mongodb.com/a6cf9cc/drivers/docsworker/060920-drivers-page-python-api-link/drivers
> replace api.mongodb.com link for pymongo API docs

- source/use-cases/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCSP-11098
https://docs-mongodbcom-staging.corp.mongodb.com/bdd0989/drivers/docsworker-xlarge/DOCSP-11098-fix-csfle-python/use-cases/client-side-field-level-encryption-guide
- Fixed the anchor link.
- Verified that the python example still works as expected.
> DOCSP-11098 fix csfle python

- source/includes/atlas-connect-blurb.rst
- source/includes/help-links-java.rst
- source/java.txt
- source/reactive-streams.txt
- source/scala.txt
https://jira.mongodb.org/browse/DOCSP-11544
[Java](https://docs-mongodbcom-staging.corp.mongodb.com/3eaeede/drivers/docsworker-xlarge/DOCSP-11544-java-landing-updates/java/)
[Reactive Streams](https://docs-mongodbcom-staging.corp.mongodb.com/3eaeede/drivers/docsworker-xlarge/DOCSP-11544-java-landing-updates/reactive-streams/)
[Scala](https://docs-mongodbcom-staging.corp.mongodb.com/3eaeede/drivers/docsworker-xlarge/DOCSP-11544-java-landing-updates/scala/)
> DOCSP-11544: update Java landing pages for 4.1

- source/php-libraries.txt
With a recent release, Doctrine MongoDB ODM dropped usage of the legacy PHP driver in favour of the current driver. Information regarding compatibility libraries has been removed.
> Rewrite Doctrine MongoDB ODM chapter

- source/includes/mongodb-compatibility-table-cxx.rst
https://jira.mongodb.org/browse/DOCSP-10572
https://docs-mongodbcom-staging.corp.mongodb.com/3ce6fc7/drivers/docsworker-xlarge/DOCSP-10572-cxx-matrix-update/cxx
> DOCSP-10572: remove c++ 3.5 from server 4.2 compat

- source/rust.txt
https://jira.mongodb.org/browse/DOCSP-12465
https://docs-mongodborg-staging.corp.mongodb.com/506eafa/drivers/docsworker-xlarge/DOCSP-12465-rust-connection-examples/rust/#connect-to-mongodb-atlas
> DOCSP-12465 rust connection examples

- source/includes/language-compatibility-table-java-rs.rst
- source/includes/language-compatibility-table-java.rst
- source/includes/mongodb-compatibility-table-java.rst
- source/java.txt
Anonymous footnotes spread across multiple include files are problematic. To maintain sanity, it's helpful to name the footnotes and footnote references so that the backend can match them up.
https://jira.mongodb.org/browse/DOP-931
https://docs-mongodborg-staging.corp.mongodb.com/DOP-931/drivers/cgoecknerwald/master/
https://docs-mongodborg-staging.corp.mongodb.com/master/drivers/cgoecknerwald/master/
> DOP-931: Name footnotes in included files

- source/use-cases/client-side-field-level-encryption-guide.txt
- source/use-cases/client-side-field-level-encryption-local-key-to-kms.txt
https://jira.mongodb.org/browse/DOCSP-12738
https://docs-mongodbcom-staging.corp.mongodb.com/2ee9f35/drivers/docsworker-xlarge/DOCSP-12738-placeholder-use-cases/use-cases/client-side-field-level-encryption-guide
https://docs-mongodbcom-staging.corp.mongodb.com/2ee9f35/drivers/docsworker-xlarge/DOCSP-12738-placeholder-use-cases/security/client-side-field-level-encryption-local-key-to-kms
Temporary solution does not expand the "Security" nav, but provides the content where it used to exist and links reference the security directory.
> DOCSP-12738: add use-cases pages back temporarily

- source/csharp.txt
- source/includes/language-compatibility-table-csharp.rst
https://jira.mongodb.org/browse/DOCS-13936
https://docs-mongodbcom-staging.corp.mongodb.com/e597ad6/drivers/docsworker-xlarge/DOCS-13936-update-csharp-links/csharp
> DOCS-13936: update csharp links for 2.11 driver

- source/includes/steps-fle-convert-to-a-remote-master-key.yaml
- source/security/client-side-field-level-encryption-local-key-to-kms.txt
- source/use-cases/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCSP-12976
https://docs-mongodbcom-staging.corp.mongodb.com/df4a744/drivers/docsworker-xlarge/DOCSP-12796-remove-region-aws/security/client-side-field-level-encryption-local-key-to-kms
> DOCSP-12976: remove aws region from KMS options

- source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml
- source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml
This includes the config information for the dotnet driver to use gcp as a remote kms. It also cleans up the Node.js notes about not supporting GCP and Azure.
https://jira.mongodb.org/browse/DOCSP-13041
https://docs-mongodbcom-staging.corp.mongodb.com/336656f/drivers/docsworker-xlarge/DOCSP-13041/security/client-side-field-level-encryption-local-key-to-kms#specify-your-google-cloud-kms-credentials
> GCP dotnet info

- source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml
- source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml
https://jira.mongodb.org/browse/DOCSP-13100
https://docs-mongodbcom-staging.corp.mongodb.com/b05c620/drivers/docsworker-xlarge/DOCSP-13100-pymongocrypt-link/security/client-side-field-level-encryption-local-key-to-kms
> DOCSP-13100: add link to pymongocrypt build instructions

- source/use-cases/client-side-field-level-encryption-guide.txt
- source/use-cases/client-side-field-level-encryption-local-key-to-kms.txt
https://jira.mongodb.org/browse/DOCSP-13087
https://docs-mongodbcom-staging.corp.mongodb.com/feb8bd0/drivers/docsworker-xlarge/DOCSP-13087-copy-guides/use-cases/client-side-field-level-encryption-guide
https://docs-mongodbcom-staging.corp.mongodb.com/feb8bd0/drivers/docsworker-xlarge/DOCSP-13087-copy-guides/use-cases/client-side-field-level-encryption-local-key-to-kms
> DOCSP-13087: copy over CSFLE guides from security

- source/includes/language-compatibility-table-java.rst
None
https://docs-mongodbcom-staging.corp.mongodb.com/432fb1c/drivers/docsworker-xlarge/111320-java-language-compat-update-4.1/java/#language-compatibility
> update Java language compatibility table for 4.1

- source/includes/mongodb-compatibility-table-swift.rst
This removes MongoDB 3.4 from the compatibility table for the Swift driver.
https://jira.mongodb.org/browse/DOCSP-13206
https://docs-mongodbcom-staging.corp.mongodb.com/1ef7c40/drivers/docsworker-xlarge/DOCSP-13206/swift/#compatibility
> Swift 1.0 only supports 3.6+

- source/includes/language-compatibility-table-php.rst
- source/includes/php-mongodb-compatibility-table.rst
This adds the upcoming PHP driver releases to the compatibility tables. Release candidates have been published, with final releases being rolled out next week.
> Update compatibility tables for PHP

- source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
This adds go driver coverage for using AWS KMS.
https://jira.mongodb.org/browse/DOCSP-13212
https://docs-mongodbcom-staging.corp.mongodb.com/97d7715/drivers/docsworker-xlarge/DOCSP-13212/security/client-side-field-level-encryption-local-key-to-kms#specify-the-aws-kms-provider-credentials
> go aws csfle

- source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
- source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml
- source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml
I combined both tickets into one. This includes the information required for both gcp and azure kms. It differs slightly from the companion project, but is close enough I don't think there will be any confusion.
https://jira.mongodb.org/browse/DOCSP-13040
https://jira.mongodb.org/browse/DOCSP-13036
https://docs-mongodbcom-staging.corp.mongodb.com/1f73bc3/drivers/docsworker-xlarge/DOCSP-13036/security/client-side-field-level-encryption-local-key-to-kms#specify-the-azure-credentials
> add gcp and azure kms

- source/includes/help-links-java.rst
- source/includes/language-compatibility-table-java-rs.rst
- source/includes/language-compatibility-table-java.rst
- source/includes/language-compatibility-table-scala.rst
- source/includes/mongodb-compatibility-table-java-rs.rst
- source/includes/mongodb-compatibility-table-java.rst
- source/includes/mongodb-compatibility-table-scala.rst
- source/java.txt
- source/reactive-streams.txt
- source/scala.txt
https://jira.mongodb.org/browse/DOCSP-13990
https://docs-mongodbcom-staging.corp.mongodb.com/46c7f16/drivers/docsworker-xlarge/DOCSP-13990-update-java-42/java
https://docs-mongodbcom-staging.corp.mongodb.com/46c7f16/drivers/docsworker-xlarge/DOCSP-13990-update-java-42/reactive-streams
https://docs-mongodbcom-staging.corp.mongodb.com/46c7f16/drivers/docsworker-xlarge/DOCSP-13990-update-java-42/scala
> DOCSP-13990: update java driver links for v4.2

- source/pymongo.txt
This changes the version under "install a specific version" to the latest version, should a user copy that instead of the default install.
https://jira.mongodb.org/browse/DOCS-14218
https://docs-mongodbcom-staging.corp.mongodb.com/fe9b466/drivers/docsworker-xlarge/DOCS-14218/pymongo/
> DOCS-14218: install latest pymongo version

- config/redirects
*This addresses redirection chains in the docs-ecosystem repo as part of the SEO project*
- Organizes redirects and removes redirect chains (organization was required to *find* the redirection chains)
- Ensures all redirects to docs.mongodb.com/ pages point at the canonical (with `/`) URL to avoid extra redirect steps
https://jira.mongodb.org/browse/DOP-1883
Generated redirects file: [drivers-redirects.txt](https://github.com/mongodb/docs-ecosystem/files/6103518/drivers-redirects.txt)
> DOP-1883: clean up redirects for SEO

- source/index.txt
https://jira.mongodb.org/browse/DOP-1883
https://docs-mongodborg-staging.corp.mongodb.com/85ec5ca/drivers/docsworker-xlarge/trivial-node-TOC/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=605a40cd2723a9e448ebc55c
> DOP-1883: update TOC link to use canonical node docs URL

- source/includes/language-compatibility-table-c.rst
- source/includes/language-compatibility-table-csharp.rst
- source/includes/language-compatibility-table-cxx.rst
- source/includes/language-compatibility-table-java.rst
- source/includes/language-compatibility-table-motor.rst
- source/includes/language-compatibility-table-php.rst
- source/includes/language-compatibility-table-python.rst
- source/includes/language-compatibility-table-scala.rst
- source/includes/mongodb-compatibility-table-c.rst
- source/includes/mongodb-compatibility-table-csharp.rst
- source/includes/mongodb-compatibility-table-cxx.rst
- source/includes/mongodb-compatibility-table-go.rst
- source/includes/mongodb-compatibility-table-java.rst
- source/includes/mongodb-compatibility-table-motor.rst
- source/includes/mongodb-compatibility-table-python.rst
- source/includes/mongodb-compatibility-table-rust.rst
- source/includes/mongodb-compatibility-table-scala.rst
- source/includes/mongodb-compatibility-table-swift.rst
- source/includes/php-mongodb-compatibility-table.rst
- While pasting all the links, I noticed that only the 2 python pages have a 2 level TOC (both show MongoDB and Language Compatibility) 
- Ruby Driver Compatibility tables don't have "Version" in the column header
- Node Driver will be done in a different PR
https://jira.mongodb.org/browse/DOCSP-15475
https://docs-mongodbcom-staging.corp.mongodb.com/8da4153/drivers/docsworker-xlarge/DOCSP-15475-ColumnSizing/c/#compatibility
https://docs-mongodbcom-staging.corp.mongodb.com/8da4153/drivers/docsworker-xlarge/DOCSP-15475-ColumnSizing/cxx/#compatibility
https://docs-mongodbcom-staging.corp.mongodb.com/8da4153/drivers/docsworker-xlarge/DOCSP-15475-ColumnSizing/csharp/#compatibility
https://docs-mongodbcom-staging.corp.mongodb.com/8da4153/drivers/docsworker-xlarge/DOCSP-15475-ColumnSizing/go/#com …
> DOCSP-15475 updated compat tables column and row names 

- source/security/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCS-14405
https://docs-mongodbcom-staging.corp.mongodb.com/598ea83/drivers/docsworker-xlarge/DOCS-14405-CSFLE-libmongocrypt/security/client-side-field-level-encryption-guide/
> DOCS-14405: Update golang instructions for libmongocrypt

- source/community-supported-drivers.txt
Added Kotlin to the list of community drivers.
https://jira.mongodb.org/browse/DOCSP-16096
https://docs-mongodbcom-staging.corp.mongodb.com/5fb4b85/drivers/docsworker-xlarge/DOCSP-16096-AddingKotlinDriver/community-supported-drivers/
> DOCSP-16096 added Kotlin to community drivers

- source/c.txt
- source/csharp.txt
- source/cxx.txt
- source/go.txt
- source/includes/serverless-compatibility.rst
- source/java.txt
- source/motor.txt
- source/php.txt
- source/pymongo.txt
- source/reactive-streams.txt
- source/rust.txt
- source/scala.txt
- source/swift.txt
Added a note to redirect readers to the atlas page about connecting to a serverless instance.
Once approved here, I'll create a PR for the Node.js and Java driver docs repos.
Note: the link to the atlas page does not work yet, but here is their current link in staging: https://docs-atlas-staging.mongodb.com/cloud-docs/docsworker-xlarge/DOCSP-15986/reference/serverless-instance-limitations/#minimum-driver-versions-for-serverless-instances  
https://jira.mongodb.org/browse/DOCSP-DOCSP-17382
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17382-ServerlessCompatibility/c/#connect-to-mongodb-atlas
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17382-ServerlessCompatibility/cxx/#connect-to-mongodb-atlas …
> DOCSP-17382 connecting to serverless

- source/java-drivers.txt
- source/java.txt
This makes the /java page the same as /java-drivers and updates the link to the new /java/sync site for the standard java driver
https://jira.mongodb.org/browse/DOCSP-17290
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17290/java-drivers/
> DOCSP-17290: expose java/sync

- source/includes/mongodb-compatibility-table-java-rs.rst
None
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/071221-quick-fix/reactive-streams/
> fix version

- source/includes/language-compatibility-table-php.rst
A user reported this in https://github.com/mongodb/mongo-php-library/issues/845
https://jira.mongodb.org/browse/PHPC-1685
https://jira.mongodb.org/browse/PHPLIB-589
> PHPC-1685 and PHPLIB-589: ext-1.10 and lib-1.9 do not support PHP 7.0

- source/includes/mongodb-compatibility-table-go.rst
Updated the Go-lang compatibility to include v1.7
https://jira.mongodb.org/browse/DOCSP-17734
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17734-Go1.7Compatibility/go/#compatibility
> DOCSP-17734 go compatibility table

- source/security/client-side-field-level-encryption-guide.txt
This fixes the broken link to the go project.
n/a
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/fix-go-link/security/client-side-field-level-encryption-guide/#download-example-project
> fixes go link

- source/includes/mongodb-compatibility-table-c.rst
Adds version 1.19 with full 5.0 support.
https://jira.mongodb.org/browse/DOCSP-18192
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-18192/c/#compatibility
> DOCSP-18192: add new version to compat table

- source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
- source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml
- source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml
- source/includes/substitute-placeholders.rst
Added note about substitution needed on the CSFLE KMS page.
https://jira.mongodb.org/browse/DOCSP-14648
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612d35177dcf0129302b8f35
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-14648-CSFLETemplateClarification/security/client-side-field-level-encryption-local-key-to-kms/
> DOCS-14648 CSFLE template clarification

- snooty.toml
- source/includes/language-compatibility-table-rust.rst
- source/includes/mongodb-compatibility-table-rust.rst
Updates Rust to 2.0
https://jira.mongodb.org/browse/DOCS-14780
**Paste your workerpool job link here**
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6138ff21c608bec57f8a6fc4
> rust 2.0 release

- config/redirects
This redirects drivers/go to drivers/go/current/ and into the new docset.
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6144eca1c608bec57f3c4fa7
https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/NNNNN/index.html
> redirect to new docset

- .github/pull_request_template.md
- source/index.txt
https://jira.mongodb.org/browse/DOCSP-18828
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61536b498670bd27318f1519
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-18828-rust-order/rust/
> DOCSP-18828 rust order

- source/includes/mongodb-compatibility-table-swift.rst
Updated the Swift compatibility table to include 1.1.0 and 1.2.0.
I also confirmed with Kaitlin for each versions compatibility. 
Note: I was told 1.2.0 will be released this week (maybe today), so I will wait till I see the release message before merging.
https://jira.mongodb.org/browse/DOCSP-19329
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=618aeb56c13055282d8125dc
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19329-Swift1.1.0/swift/#compatibility
> DOCSP-19329 swift compatibility table update

- source/includes/language-compatibility-table-php.rst
- source/includes/mongodb-compatibility-table-php.rst
- source/php.txt
This also renames the server compatibility table to be consistent with the files for other drivers.
https://jira.mongodb.org/browse/DOCSP-19644
N/A
N/A
> DOCSP-19644: Update PHP driver language and server compat tables

- source/includes/language-compatibility-table-csharp.rst
This adds a note that certain versions of the driver require a patch version of .Net 4.5. This has already been reviewed by the C# lead.
https://jira.mongodb.org/browse/DOCS-14936
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=619685755314b0809f9f2aea
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-14936/csharp/#language-compatibility
> add patch version note

- source/security/client-side-field-level-encryption-guide.txt
None
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=619d39625314b0809f220478
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/112321-mongodbcrypt/security/client-side-field-level-encryption-guide/#implementation
> Fix mongo-crypt -> mongodb-crypt

- source/swift.txt
https://jira.mongodb.org/browse/DOCS-14845
The new description is not especially engaging, but I created a ticket to update the text to something better across drivers: https://jira.mongodb.org/browse/DOCSP-19933
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61a7f6555314b0809f8a9f8f
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-14845-swift-driver-clarification/swift/
> DOCS-14845: clarify swift driver usage and link to Realm iOS

- source/swift.txt
I noticed that the checkmarks for the swift page went away, and it was in the build logs. Compare [staging](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/build-errors/swift/#compatibility) to [live](https://docs.mongodb.com/drivers/swift/#compatibility).
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61b0d3045314b0809f841592
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/build-errors/swift/#compatibility
> add checkmark for swift

- source/includes/language-compatibility-table-csharp.rst
- source/includes/mongodb-compatibility-table-rust.rst
- source/rust.txt
This corrects a typo I found on the C# language compatibility page, and updates the Rust page and compatibility.
https://jira.mongodb.org/browse/DOCS-14985
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61b9093fc52f2a460f96e8cd
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-14985/rust/#compatibility
> Docs 14985

- source/includes/mongodb-compatibility-table-php.rst
MongoDB 5.1 compatibility was previously added for this ext/lib version in https://github.com/mongodb/docs-ecosystem/commit/a423932862cc52a3890e92014f97b5de0dc83edf; however, the actual extension release is tied to libmongoc 1.20. Although that release includes KMIP support for CSFLE, full support for MongoDB 5.1 will not come until libmongoc 1.21 (tentatively PHP ext-1.13 and lib-1.12).
https://jira.mongodb.org/browse/DOCSP-20087
> DOCSP-20087: Do not list ext-1.12 and lib-1.11 as compatible with MongoDB 5.1

- source/c.txt
- source/csharp.txt
- source/cxx.txt
- source/java-drivers.txt
- source/java.txt
- source/motor.txt
- source/php.txt
- source/pymongo.txt
- source/python.txt
- source/reactive-streams.txt
- source/rust.txt
- source/scala.txt
- source/swift.txt
[Planning document](https://docs.google.com/document/d/1hWScrmE6EVK22WN0ATcVb29emFT_uzdsyosonm7_7Co/edit#)
This PR updates the intros for the following drivers, all within the docs-ecosystem repo:
- [C Driver </c>](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19933/c/)
- [C++ Driver </cxx>](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19933/cxx/)
- [C# and .NET Driver </csharp>](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19933/csharp/)
- [Java Drivers parent page </java-drivers>](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19933/java-drivers/)
- Reactive Streams Driver </reactive-streams>
- [PHP Driver …
> (DOCSP-19933) Improve and standardize intro text for drivers

- source/rust.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-22034>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-22034/rust/
> add link to rust driver manual

- config/redirects
- source/includes/mongodb-compatibility-table-rust.rst
- source/includes/mongodb-compatibility-table-swift.rst
- source/index.txt
Both CSFLE pages from docs-ecosystem redirect to the main CSFLE landing page on the Server manual.
This content currently only exists in v6.0 which is a future version. Ticketed future work in https://jira.mongodb.org/browse/DOCSP-22897
JIRA - <https://jira.mongodb.org/browse/DOCSP-22076>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
mut-redirects produced these redirects from the file:
```
Redirect 301 /docs/drivers/security https://mongodb.com/docs/v6.0/core/security-client-side-encryption/
Redirect 301 /docs/drivers/security/client-side-field-level-encryption-guide https://mongodb.com/docs/v6.0/core/security-client-side-encryption/
Redirect 301 …
```
> DOCSP-22076: CSFLE redirects

- source/includes/stable-api-snippets/java-rs-client.java
- source/includes/stable-api-snippets/pymongo-client.py
- source/includes/stable-api-snippets/scala-client.scala
Issue: snooty does not replace source constants in code-block component.
Fix: Replace source constant with value.
JIRA - None
Staging:
[PyMongo](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/091222-fix-version-constant-in-code/pymongo/#stable-api)
[Scala](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/091222-fix-version-constant-in-code/scala/#stable-api)
[Java RS](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/091222-fix-version-constant-in-code/reactive-streams/#stable-api)
> 091222: Fix source constant in code

- snooty.toml
Fixing current JVM driver version links to GH pages.
JIRA - None
Staging - 
[Reactive Streams](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/101222-update-rs-version/reactive-streams/#introduction)
[Scala](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/101222-update-rs-version/scala/#introduction)
> Update source constant for JVM driver versions)

- source/includes/mongodb-compatibility-table-rust.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-26394>
Staging - <https://docs-mongodborg-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-26394-remove-rust-1.x/>
> DOCSP-26394 Remove Rust 1.x from Compatibility Table

- source/c.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27193>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-27193-https-c-driver/c/
> DOCSP-27193: update c docs links to use https

- source/includes/mongodb-compatibility-table-rust.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-28339>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-28339/rust/#compatibility>
> DOCSP-28339: Adding Rust 2.4 to the compatibility table.

- source/includes/connection-snippets/scram/php-connection-no-stableapi.php
- source/includes/connection-snippets/scram/php-connection.php
- source/php.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28326
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-28326-php-stableapi/php/#connect-to-mongodb-atlas
- [N/A] Are all the links working?
> DOCSP-28326: add stableapi to php connection snippet

- source/c.txt
- source/cxx.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-28835>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-28835/c/> and <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-28835/cxx/>
> DOCSP-28835: Added links for C and C++ driver pages

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-28488>
Staging - None
Comments refer to the CSV attached to https://jira.mongodb.org/browse/DOCSP-28477
mut-redirects output diff:
```
9a10
> Redirect 301 /docs/drivers/perl https://www.mongodb.com/docs/drivers/community-supported-drivers/
116c117
< Redirect 301 /docs/ecosystem/drivers/ruby https://www.mongodb.com/docs/drivers/ruby/
---
> Redirect 301 /docs/ecosystem/drivers/ruby https://www.mongodb.com/docs/ruby-driver/current/
119c120
< Redirect 301 /docs/ecosystem/drivers/perl/ https://www.mongodb.com/docs/drivers/
---
> Redirect 301 /docs/ecosystem/drivers/perl/ https://www.mongodb.com/docs/drivers/community-supported-drivers/
121c122,127
< …
```
> DOCSP-28488: create redirects for bad urls

- source/php-libraries.txt
https://github.com/traderinteractive/mongo-queue-php has the wrong link, it links to a fork by a user rather than the main https://github.com/purekid/mongodm hasn't been updated since 2017, should be removed https://github.com/bjori/mongo-php-transistor hasnt been updated since 2016, should be removed https://github.com/mongator/mongator/ hasn't been updated since 2014, should be removed https://github.com/aleksmitov/MongoFilesystem hasn't been updated since 2015, should be removed https://github.com/mongofill/mongofill has been archived and isn't maintained since 2016, removing  Adding https://github.com/PHPSocialNetwork/phpfastcache  Adding XHGUI
JIRA - …
> Updating PHP libraries, 2023

- source/index.txt
Ticket completed, but updating link per Alex B.'s Jira comment.
There are errors in staging because the icons are pulled in from docs-assets for the deployed site, but not for staging.
JIRA - https://jira.mongodb.org/browse/DOCS-16146
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/docs-16146-update-link/
> docs-16146 - update link

- source/php.txt
This is analogous to reminding users to load the extension in php.ini. Both are also covered in the linked PHPLIB docs, but it makes sense to duplicate the information here for users that don't click through.
JIRA - <https://jira.mongodb.org/browse/DOCSP-31115>
> DOCSP-31115: Demonstrate including the Composer autoloader

- source/php-libraries.txt
The [legacy mongo extension](https://github.com/mongodb/mongo-php-driver-legacy) for PHP is EOL since February 2022. The lib that were not updated to support the new [`ext-mongodb`](https://pecl.php.net/package/mongodb) must not be highlighted.
Adding some new libs and components that are actively maintained and used.
JIRA - <https://jira.mongodb.org/browse/PHPORM-26>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
> PHPORM-26: Remove legacy projects

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-301714>
Staging - None
Added redirects for the malformed URLs that refer to this repo.
mut-redirects output diff:
```
110,113c110,114
< Redirect 301 /docs/ecosystem/use-cases/pre-aggregated-reports https://www.mongodb.com/developer/
< Redirect 301 /docs/ecosystem/tutorial/authenticate-with-java-driver https://www.mongodb.com/developer/
< Redirect 301 /docs/ecosystem/use-cases/client-side-field-level-encryption-guide https://www.mongodb.com/docs/manual/core/csfle/
< Redirect 301 /docs/ecosystem/tools/http-interfaces https://www.mongodb.com/developer/
---
> Redirect 301 /docs/ecosystem/use-cases/pre-aggregated-reports/ https://www.mongodb.com/developer/ …
```
> DOCSP-30714: fix June 2023 404s

- source/about-compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32358>
Staging:
- [Modifications to existing section](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-32358-component-compatibility/about-compatibility/#mongodb-compatibility-tables-1)
- [New section
](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-32358-component-compatibility/about-compatibility/#component-compatibility-tables)
> DOCSP-32358: add information about component compatibility tables

- source/index.txt
Adds mention of Atlas to the top of the drivers landing page as part of the Atlas-centric Top 250 initiative.
Build: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650af8c2492df295cf198d7a
JIRA - https://jira.mongodb.org/browse/DOCSP-32292?filter=46607
Staging - https://preview-mongodbsarahsimpers.gatsbyjs.io/drivers/DOCSP-32292/
> (DOCSP-32292) Adds mention of Atlas to drivers landing page

- source/kotlin-drivers.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-26721>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-26721-add-kotlin-sdk-link/kotlin-drivers/
> DOCSP-26721: Add Kotlin SDK link

- snooty.toml
- source/python.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32303>
Staging - <https://preview-mongodbcarriecwk.gatsbyjs.io/drivers/DOCSP-32303/python/>
Build - <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6525b179885de6b26b4f0d69>
> (DOCSP-32303) includes info about connecting an application using driver to atlas

- source/c.txt
- source/includes/connection-snippets/scram/c-connection-no-stable-api.c
- source/includes/connection-snippets/scram/c-connection.c
JIRA - <https://jira.mongodb.org/browse/DOCSP-34260>
Staging - 
- [stable api](https://preview-mongodbrustagir.gatsbyjs.io/drivers/DOCSP-34260-update-c-code-memory-leak/c/#connect-to-mongodb-atlas)
- [no stable api](https://preview-mongodbrustagir.gatsbyjs.io/drivers/DOCSP-34260-update-c-code-memory-leak/c/#connect-to-mongodb-atlas-without-the-stable-api)
> DOCSP-34260: fix c code for memory leak

- snooty.toml
- source/csharp-drivers.txt
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-34255
Staging - https://preview-mongodbmongokart.gatsbyjs.io/drivers/docsp-34255-ef-links/csharp-drivers/
> docsp-34255 - add ef links

- source/about-compatibility.txt
- source/includes/driver-compatibility-caveat.rst
- source/includes/stable-api-notice.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-33957>
Staging:
- [Stable API](https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-33957-alas-and-cleanup/c/#connect-to-mongodb-atlas-without-the-stable-api) (scroll up to see the admonition)
- [Compatibility Tables](https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-33957-alas-and-cleanup/about-compatibility/#mongodb-compatibility-tables)
> DOCSP-33957: Alas but one fixes

- source/csharp-drivers.txt
- source/index.txt
- source/java-drivers.txt
- source/php-drivers.txt
- source/pymongo.txt
- source/python-drivers.txt
Hey @mongoKart ! Would you please review this PR and merge it if everything looks good? Please edit the descriptions to make them more accurate or descriptive as you see fit. I mostly copied and pasted from text on the page; the description should be a short, general description of each page.
Thanks!
Sarah
JIRA - https://jira.mongodb.org/browse/DOCSP-33172
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/drivers/DOCSP-33172/csharp-drivers/>
Build log - <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655d289d13dc9d16eae14afd>
> DOCSP-33172 added meta description for top 250 pages in docs-ecosystem

- REVIEWING.md
- source/php-libraries.txt
Includes the same update to REVIEWING.md as in this [Java docs PR](https://github.com/mongodb/docs-java/pull/509).
JIRA - <https://jira.mongodb.org/browse/DOCSP-35392>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-35392-laravel-docs-link/php-libraries/
Relevant changes:
https://github.com/mongodb/docs-ecosystem/pull/940/files?diff=split&w=1#diff-9b46e5245116cd170b22d0944fa13d34aeadcc33692dd10bc8817f0514fe98e6R63-R67
> DOCSP-35392: update laravel docs link

- config/redirects
- snooty.toml
- source/includes/help-links-php.rst
- source/index.txt
- source/php.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35623>
Staging:
- [PHP landing page](https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-35623-rename-php-landing/php/)
Note: the [index page](https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-35623-rename-php-landing/php/) link for PHP doesn't work due to how the button-type components are rendered on staging.
Redirects diff ("<" points to the redirects currently in the deployed branch, ">" points to the redirects in this PR):
```
140c140
< Redirect 301 /docs/drivers/drivers/php/ https://www.mongodb.com/docs/drivers/php-drivers/
---
> Redirect 301 /docs/drivers/drivers/php/ https://www.mongodb.com/docs/drivers/php/
149c149
< …
```
> DOCSP-35623: updates to change php-drivers URL to php

- config/redirects
Incorrectly formatted redirects were causing the deployment job to fail.
JIRA - None
Staging - None
Old
```
Redirect 301 /docs/ecosystem/drivers/node-js/ $https://www.mongodb.com/docs/drivers/node/current/
...
Redirect 301 /docs/drivers/drivers/node/ $https://www.mongodb.com/docs/drivers/node/current/
```
New:
```
Redirect 301 /docs/ecosystem/drivers/node-js/ https://www.mongodb.com/docs/drivers/node/current/
...
Redirect 301 /docs/drivers/drivers/node/ https://www.mongodb.com/docs/drivers/node/current/
```
> fix redirect syntax error

- source/kotlin-sync.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36039>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/drivers/DOCSP-36039-link-kt-sdk/kotlin-sync/
> DOCSP-36039: surface link to Realm Kotlin SDK

- source/python-drivers.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-35856
Staging - https://preview-mongodbmongokart.gatsbyjs.io/drivers/docsp-35856-generator-note/python-drivers/#tools-and-projects
> DOCSP-35856 - fastapi generator

- config/redirects
Relevant output of `mut-redirects`:
```
Redirect 301 /docs/drivers/cxx https://www.mongodb.com/docs/languages/cpp/drivers/current
Redirect 301 /docs/drivers/cxx/index https://www.mongodb.com/docs/languages/cpp/drivers/current
Redirect 301 /docs/languages/cxx https://www.mongodb.com/docs/languages/cpp/drivers/current
```
JIRA - https://jira.mongodb.org/browse/DOCSP-38350
> DOCSP-38350 - fix redirects

- config/redirects
With our upcoming `mut` release, redirects rejected by AWS S3 now show the line number in the redirects file that is a problem. So, here we resolve the issue.
Pudding proof:
```
$ mut-redirects ../docs-ecosystem/config/redirects | grep docs/drivers/tutorial/download-and-compile-cpp-driver
Redirect 301 /docs/drivers/tutorial/download-and-compile-cpp-driver https://www.mongodb.com/docs/languages/cpp/cpp-driver/current/installation/
```
If this isn't the intended redirect target, we can update as needed.
> DOP-4086: Correct download-and-compile-cpp-driver redirect

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-41223
Output of mut-redirects:
`Redirect 301 /https://www.mongodb.com/docs/drivers/pymongo/ https://www.mongodb.com/docs/languages/python/pymongo-driver/current`
> DOCSP-41223 - PyMongo redirects

- source/includes/language-compatibility-table-motor.rst
- source/includes/mongodb-compatibility-table-motor.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-43442
Staging - https://preview-mongodbmongokart.gatsbyjs.io/drivers/docsp-43442-python-version/motor/#language-compatibility
> DOCSP-43442 - Add Python 3.13

- source/includes/language-compatibility-table-php.rst
- source/includes/mongodb-compatibility-table-php.rst
- source/php-drivers.txt
Linked compatibility table to the ``docs-shared`` repo. Kept a copy of full compatibility table, including legacy versions, for reference use only, as requested in ticket. 
JIRA - <https://jira.mongodb.org/browse/DOCSP-41653>
Staging - <https://deploy-preview-995--docs-ecosystem.netlify.app/php-drivers/#compatibility>
> DOCSP-41653 PHP Update Compatibility Table Refs

- source/kotlin-drivers.txt
- source/swift.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46180
Staging - https://deploy-preview-996--docs-ecosystem.netlify.app/kotlin-drivers/
https://deploy-preview-996--docs-ecosystem.netlify.app/swift/
> DOCSP-46180: Remove Atlas Device SDK reference

- source/documentdb-support.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46894>
Staging - <https://deploy-preview-998--docs-ecosystem.netlify.app/documentdb-support/>
> DOCSP-46894 Update compat db page

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-48223>
```
Redirect 301 /docs/drivers/kotlin/ https://www.mongodb.com/docs/drivers/kotlin-drivers/
```
> DOCSP-48223: kotlin duplicate redirect

- source/about-compatibility.txt
- source/cosmosdb-support.txt
- source/documentdb-support.txt
- source/kotlin-drivers.txt
- source/motor.txt
- source/other-document-dbs.txt
- source/php-frameworks/symfony.txt
- source/php-libraries.txt
- source/ruby-drivers.txt
- source/swift.txt
- source/typescript.txt
Adds missing meta descriptions generated by the Education AI Team\n\nSOURCE: https://docs.google.com/spreadsheets/d/1fdrjF4Ms9fMl96zLiLGsYD_V38rTfPLuKs5VQk4vz6E/edit?gid=1166644539
> Add missing meta descriptions

- source/odm.txt
- source/other-document-dbs.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48458>
Staging - <https://deploy-preview-1004--docs-ecosystem.netlify.app/odm/>
Review notes - https://docs.google.com/document/d/13Z4hXqa755AhoR2V1Ok4fGit4K6V3cCRzTJ2IDcWzys/edit?tab=t.0#heading=h.toja6eogty3a
> [Docs+] MongoDB ORMs, ODMs, and Libraries

- snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCS-17017
Staging - https://deploy-preview-1007--docs-ecosystem.netlify.app/motor/
> Add deprecation banner to Motor docs
