mongodb/docs-ecosystem

source/drivers/ruby.txt, source/tutorial/ruby-mongoid-tutorial.txt
The Official Mongoid 5.0 documentation.
Can be merged.
=> Mongoid 5.0.0 Documentation

source/drivers/php.txt
See full commit messages for detailed changes.
=> Revisions for PHP driver page

source/drivers/driver-compatibility-reference.txt
@kay-kim : Added Java Driver 3.5 to compatibility matrix.
=> (DOCS-10951): Added Java Driver 3.5 compatibility.

source/drivers/driver-compatibility-reference.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/425)
=> DOCSP-1522: Motor 1.2

source/drivers/community-supported-drivers.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/428)
=> MongoDB support for Django

source/drivers/driver-compatibility-reference.txt, source/drivers/php.txt
@kay-kim : RFM for `v3.6` and `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/426)
=> (DOCS-11122): Added mongodb-1.3 PHP language compatibility.

source/drivers/php.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/432)
=> Make title consistent with other driver pages

source/drivers/php-libraries.txt
Adding this here since we're going to remove it from the PHPC readme in https://github.com/mongodb/mongo-php-driver/pull/769.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/434)
=> Add @bjori's Transistor library

source/drivers/php-libraries.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/436)
=> Oxford comma

source/drivers/driver-compatibility-reference.txt, source/drivers/php.txt, source/includes/php-mongodb-compatibility-table.rst
CR: https://mongodbcr.appspot.com/188770003/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/438)
=> DOCSP-2020: Inconsistencies in PHP compatibility tables

source/drivers/driver-compatibility-reference.txt, source/drivers/python.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/440)
=> Docs 11548a

source/drivers/driver-compatibility-reference.txt, source/drivers/scala.txt
@kay-kim : Use this instead of #443 . This includes those changes plus the Scala change. RFM for `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/444)
=> Modification of PR #443: Java and Scala Updates

config/sphinx_local.yaml, source/tools.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/446)
=> DOCSP-2485 - Update ecosystem for ODBC driver.

source/drivers/community-supported-drivers.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/447)
=> DOCS-11779: Remove MongoMapper from community-supported drivers

source/drivers/csharp.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-ecosystem/445)
=> DOCS-11737: VS 2017

README.rst
I personally installed it with --user but then I had to add ~/.local/bin to PATH.
=> giza is a required dependency

source/includes/driver-table.rst
https://jira.mongodb.org/browse/MONGOID-4565
=> Add Mongoid to the list of drivers.

source/drivers/driver-compatibility-reference.txt, source/drivers/python.txt
Staged:
- https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/rk-mongo/DOCS-12644/drivers/driver-compatibility-reference.html#python-driver-compatibility
- https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/rk-mongo/DOCS-12644/drivers/python.html
=> DOCS-12644: PyMongo 3.8.0

source/drivers.txt, source/drivers/c.txt, source/drivers/cxx.txt, source/drivers/driver-compatibility-reference.txt, source/drivers/java.txt, source/drivers/node.txt, source/includes/driver-table.rst, source/includes/extracts-additional-information.yaml, source/includes/language-compatibility-table-c.rst, source/includes/language-compatibility-table-cxx.rst, source/includes/language-compatibility-table-java.rst, source/includes/language-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-c.rst, source/includes/mongodb-compatibility-table-cxx.rst, source/includes/mongodb-compatibility-table-java.rst, source/includes/mongodb-compatibility-table-node.rst
https://jira.mongodb.org/browse/DOCSP-5398
https://jira.mongodb.org/browse/DOCSP-5399
https://jira.mongodb.org/browse/DOCSP-5400
https://jira.mongodb.org/browse/DOCSP-5401
https://jira.mongodb.org/browse/DOCSP-5520
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/drivers-landing/index.html
C: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/drivers-landing/drivers/c.html
C++: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/drivers-landing/drivers/cxx.html
Java: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/drivers-landing/drivers/java.html
Node: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/drivers-landing/drivers/node.html
=> Drivers landing pages

source/includes/mongodb-compatibility-table-cxx.rst
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/nathanleniz/DOCSP-3504/drivers/driver-compatibility-reference.html)
=> (DOCSP-3504) - Updates cxx compatibility table

source/drivers/driver-compatibility-reference.txt, source/drivers/scala.txt, source/includes/language-compatibility-table-scala.rst, source/includes/mongodb-compatibility-table-scala.rst
This applies the landing page template to the Scala landing page.
https://jira.mongodb.org/browse/DOCSP-5404
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5404-scala-landing/drivers/scala.html
=> DOCSP-5404 Update Scala driver landing page

source/drivers/driver-compatibility-reference.txt, source/drivers/node.txt, source/drivers/php.txt, source/includes/language-compatibility-table-php.rst
https://jira.mongodb.org/browse/DOCSP-5403
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5403-php-landing/drivers/php.html
=> DOCSP-5403 Update PHP landing page

source/drivers/driver-compatibility-reference.txt, source/drivers/perl.txt, source/includes/language-compatibility-table-perl.rst, source/includes/mongodb-compatibility-table-perl.rst
https://jira.mongodb.org/browse/DOCSP-5406
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-5406-perl-landing/drivers/perl.html
=> DOCSP-5406 Update Perl landing page

source/includes/language-compatibility-table-java.rst, source/includes/mongodb-compatibility-table-java.rst
=> Updated Java language and mongodb compatibility tables

source/includes/language-compatibility-table-java.rst
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/fix-note/drivers/java.html#language-compatibility
=> Fix compatibility note markup

source/drivers/c.txt, source/drivers/csharp.txt, source/drivers/cxx.txt, source/drivers/go.txt, source/drivers/java.txt, source/drivers/node.txt
https://jira.mongodb.org/browse/DOCSP-6066
https://github.com/10gen/cloud-docs/pull/914
View the various drivers pages:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/docsp-6066-atlas-connect-w-majority/drivers.html
=> DOCSP-6066 Add w=majority to all Atlas connection snippets

source/drivers/driver-compatibility-reference.txt
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/bush/update-ruby-driver-compat/drivers/driver-compatibility-reference.html#ruby-driver-compatibility
=> Update Ruby compat table on Drivers page

conf.py, source/use-cases/sensitive-data-encryption.txt
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/fle-guide-master-key/use-cases/sensitive-data-encryption.html
=> DOCSP-6486: FLE Guide local master key

conf.py, source/drivers/java.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-6654
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6654/drivers/java.html
=> DOCSP-6654: Update java docs references to point to latest (3.10 -> 3.11)

source/includes/mongodb-compatibility-table-scala.rst
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6683/index.html)
=> (DOCSP-6683) - removes duplicated text

source/use-cases/sensitive-data-encryption.txt
Intro, problem, and solution sections.
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/fle-guide-intro/use-cases/sensitive-data-encryption.html
=> FLE: intro sections

conf.py, source/use-cases/sensitive-data-encryption.txt
**JIRA:**
https://jira.mongodb.org/browse/DOCSP-6419
**Staging:**
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/fle-guide-reqs/use-cases/sensitive-data-encryption.html
=> FLE Guide - Requirements section (DOCSP-6419)

source/index.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-6783
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6783/index.html
=> DOCSP-6783 Remove Adobe Experience course from index page

source/includes/steps-create-data-encryption-key.yaml, source/use-cases/sensitive-data-encryption.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-6562
Staging: https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/fle-guide-data-keys/use-cases/sensitive-data-encryption.html
=> DOCSP-6562 FLE guide data keys

source/drivers/perl.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6542/drivers/perl.html)
=> better deprecation message for perl driver

source/drivers/go.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6470/drivers/go.html)
Updates godoc link to avoid redirect
=> update link to godoc to avoid redirect

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/index.txt, source/use-cases.txt, source/use-cases/sensitive-data-encryption.txt
- [(DOCSP-6740): FLE Use Case - Client Setup](https://jira.mongodb.org/browse/DOCSP-6740)
- [(DOCSP-6485): Document how to migrate from local to remote KMS](https://jira.mongodb.org/browse/DOCSP-6485)
- [D. Create the MongoDB Client](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/nick/fle-guide/use-cases/sensitive-data-encryption.html#d-create-the-mongodb-client)
- [F. Convert to a Remote Master Key](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/nick/fle-guide/use-cases/sensitive-data-encryption.html#f-convert-to-a-remote-master-key)
=> (DOCSP-6740): FLE Guide

source/use-cases/sensitive-data-encryption.txt
staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6484-CRUD-FieldLevelEncryption/use-cases/sensitive-data-encryption.html#d-perform-encrypted-read-write-operations
jira: https://jira.mongodb.org/browse/DOCSP-6484?filter=-1
=> Docsp 6484 crud field level encryption

conf.py, source/includes/steps-create-data-encryption-key.yaml, source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/use-cases/sensitive-data-encryption.txt
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/nick/fle-guide/use-cases/sensitive-data-encryption.html#f-convert-to-a-remote-master-key
=> (FLE): Unification Pass

source/includes/driver-table.rst
JIRA: https://jira.mongodb.org/browse/DOCSP-6543
STAGE: https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6543-change-cxx11/index.html
=> C++11 => C++ in drivers table

source/includes/steps-create-data-encryption-key.yaml, source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/use-cases/sensitive-data-encryption.txt
Jira Ticket: https://jira.mongodb.org/browse/DOCSP-6986?filter=-1
~Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6986-CSFLE-Nodejs-implementation/use-cases/sensitive-data-encryption.html~
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6986-Nodejs-CSFLE/use-cases/sensitive-data-encryption.html
=> Docsp 6986 nodejs csfle

source/connectors/kafka-connect-migration.txt, source/connectors/kafka-installation.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-6632
Stage:
https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6632-installation-guide/connectors/kafka-installation.html
=> DOCSP-6632: Kafka connector guide - installation

conf.py, source/includes/steps-create-data-encryption-key.yaml, source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/sensitive-data-encryption.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-6971
STAGE:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6971-csfle-improvements/use-cases/sensitive-data-encryption.html
=> fixes to CSFLE use-case guide

source/drivers/php.txt
https://jira.mongodb.org/browse/PHPC-1312
=> PHPC-1312: Advise users to use 64-bit environments if possible

config/redirects
Added redirect from `use-cases/sensitive-data-encryption` to `/use-cases/client-side-field-level-encryption-guide`
=> added redirect

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/client-side-field-level-encryption-guide.txt
For now I've linked to the original Python CSFLE ticket but I can open a new one if requested.
=> DOCSP-6987 Make Python CSFLE examples more idiomatic

source/connectors/kafka-docker-example.txt, source/connectors/kafka-sink-cdc.txt, source/connectors/kafka-sink-data-formats.txt, source/connectors/kafka.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-6636
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-6636-kafka-docker-example/connectors/kafka-docker-example.html
=> DOCSP-6636: Kafka Docker Example

conf.py
JIRA: https://jira.mongodb.org/browse/DOCSP-7487
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7487-use-https/index.html
=> DOCSP-7487 use https instead of http for extlinks

conf.py, source/drivers/csharp.txt
JIRA: https://jira.mongodb.org/browse/DOCS-13160
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCS-13160-update-csharp-links/drivers/csharp.html
=> DOCS-13160: update csharp links to point to 2.9 driver

source/drivers/c.txt, source/drivers/csharp.txt, source/drivers/cxx.txt, source/drivers/go.txt, source/drivers/java.txt, source/drivers/motor.txt, source/drivers/node.txt, source/drivers/perl.txt, source/drivers/php.txt, source/drivers/pymongo.txt, source/drivers/scala.txt, source/drivers/specs.txt, source/includes/driver-table.rst, source/platforms/amazon-ec2.txt, source/tools/hadoop.txt, source/tutorial/backup-and-restore-mongodb-on-amazon-ec2.txt, source/use-cases/client-side-field-level-encryption-guide.txt, tools/compact_extlinks.py
Substitute full URLs with extlinks when present.
Staging: https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/compact-links/index.html
=> Compact links in docs-ecosystem

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/client-side-field-level-encryption-guide.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-7589
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7589-csfle-nodejs-improvements/use-cases/client-side-field-level-encryption-guide.html
=> DOCSP-7589: Update NodeJS examples in CSFLE to be more idiomatic

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/client-side-field-level-encryption-guide.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-7658
Staging: https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7658-java-csfle-fixes/use-cases/client-side-field-level-encryption-guide.html
=> DOCSP-7658: Java CSFLE fixes

source/use-cases/client-side-field-level-encryption-guide.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-7006
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7006-csfle-link-server-json-schema/use-cases/client-side-field-level-encryption-guide.html
=> DOCSP-7006 fix admonition, add link to server-side encryption schema

source/includes/connection-snippets/x509-snippets/csharp-connection.cs
Ticket: https://jira.mongodb.org/browse/DOCSP-7887
x509 client connection with csharp
=> (DOCSP-7887): added csharp x509 code

source/includes/connection-snippets/x509-snippets/node-connection.js
Ticket: https://jira.mongodb.org/browse/DOCSP-7890
=> (DOCSP-7890): added node x509 connection snippet

source/includes/connection-snippets/x509-snippets/java-connection.java
Ticket: https://jira.mongodb.org/browse/DOCSP-7889
=> (DOCSP-7889): added java x509 snippet

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/client-side-field-level-encryption-guide.txt
JIRA [DOCSP-7795](https://jira.mongodb.org/browse/DOCSP-7795)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7795-CSFLE-identify-runnable/use-cases/client-side-field-level-encryption-guide.html)
=> DOCSP-7795 - CSFLE Guide: Identify code snippet and complete runnable example

source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/index.txt, source/use-cases.txt, source/use-cases/client-side-field-level-encryption-guide.txt, source/use-cases/client-side-field-level-encryption-local-key-to-kms.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7796/index.html)
=> (DOCSP-7796): separate out kms step

source/includes/connection-snippets/x509-snippets/cpp-connection.cpp, source/includes/connection-snippets/x509-snippets/go-connection.go
Ticket: https://jira.mongodb.org/browse/DOCSP-7886
C++ reviewer(s): either @jmikola or @bazile-clyde
Docs reviewer: @zach-carr
=> (DOCSP-7886): added cpp x509 connection snippet

source/includes/connection-snippets/x509-snippets/python-connection.py
Ticket: https://jira.mongodb.org/browse/DOCSP-7893
Python reviewer(s): either @prashantmital  or @ShaneHarvey 
Docs reviewer: @zach-carr
=> (DOCSP-7893): added python client connection for x509

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/use-cases/client-side-field-level-encryption-guide.txt
JIRA: https://https://jira.mongodb.org/browse/DOCSP-7794
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7794-csfle-audience/use-cases/client-side-field-level-encryption-guide.html
=> DOCSP-7794 csfle audience

source/includes/connection-snippets/x509-snippets/ruby-connection.rb
Ticket: https://jira.mongodb.org/browse/DOCSP-7894
Python reviewer(s): either @jmikola or @p-mongo
Docs reviewer: @zach-carr
=> (DOCSP-7894): added ruby x509 snippet

source/drivers/php.txt
https://jira.mongodb.org/browse/PHPC-1467
=> PHPC-1467: Update installation instructions for PHP driver

conf.py, source/connectors/kafka.txt, source/includes/language-compatibility-table-java.rst, source/includes/mongodb-compatibility-table-java.rst
JIRA: https://jira.mongodb.org/browse/DOCSP-8038
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-8038-update-java-driver-version/drivers/java.html
=> DOCSP-8038: update java driver version to 3.12

conf.py
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCS-13279/drivers/csharp.html)
=> update csharp to latest version

conf.py, source/drivers/go.txt, source/drivers/node.txt, source/drivers/scala.txt, source/includes/language-compatibility-table-csharp.rst, source/includes/language-compatibility-table-node.rst, source/includes/language-compatibility-table-scala.rst, source/includes/mongodb-compatibility-table-csharp.rst, source/includes/mongodb-compatibility-table-go.rst, source/includes/mongodb-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-scala.rst
Please review [staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-8039/index.html)
=> (DOCSP-8039) - updates driver versions

source/includes/steps-fle-convert-to-a-remote-master-key.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/client-side-field-level-encryption-guide.txt, source/use-cases/client-side-field-level-encryption-local-key-to-kms.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-7798
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7798-csfle-diagrams/use-cases/client-side-field-level-encryption-guide.html
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-7798-csfle-diagrams/use-cases/client-side-field-level-encryption-local-key-to-kms.html
=> DOCSP-7798: CSFLE diagrams and other tweaks

config/redirects, source/drivers/c.txt, source/drivers/csharp.txt, source/drivers/cxx.txt, source/drivers/go.txt, source/drivers/java.txt, source/drivers/node.txt, source/drivers/perl.txt, source/drivers/php.txt, source/drivers/pymongo.txt, source/drivers/scala.txt
adds refs back.
For ruby, update refs in cloud for compat to .. _reference-compatibility-ruby:
=> correct redirect and add refs for cloud

source/tutorial/backup-and-restore-mongodb-on-amazon-ec2.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-8295/tutorial/backup-and-restore-mongodb-on-amazon-ec2.html)
Removes master/slave terminology
=> removes master/slave reference

source/drivers/community-supported-drivers.txt
[Preview](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCS-13362/drivers/community-supported-drivers.html)
@niccottrell could you give this a review?
=> (DOCS-13362): clean up coldfusion entries in community

config/redirects
=> fix broken redirect

source/includes/mongodb-compatibility-table-go.rst
JIRA
none
Staging
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/020520-update-golang-matrix/drivers/go.html#compatibility
=> update golang compatibility matrix for 1.3

source/drivers.txt, source/drivers/java-drivers.txt, source/drivers/reactive-streams.txt, source/includes/language-compatibility-table-java-rs.rst, source/includes/mongodb-compatibility-table-java-rs.rst
JIRA: https://jira.mongodb.org/browse/DOCSP-2157
Staging: 
New landing page for Java drivers:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-2157-reactive-streams-page/drivers/java-drivers.html
New Reactive Streams driver page:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-2157-reactive-streams-page/drivers/reactive-streams.html
=> DOCSP-2157 Java reactive streams driver page

source/drivers/csharp.txt
JIRA: https://jira.mongodb.org/browse/DOCS-12433
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/pegasus/DOCS-12433/drivers/csharp.html
=> DOCS-12433: .NET driver link fixes

conf.py, source/drivers/c.txt, source/drivers/csharp.txt, source/drivers/cxx.txt, source/drivers/go.txt, source/drivers/java.txt, source/drivers/motor.txt, source/drivers/node.txt, source/drivers/perl.txt, source/drivers/php.txt, source/drivers/pymongo.txt, source/drivers/reactive-streams.txt, source/drivers/scala.txt, source/drivers/swift.txt, source/includes/help-links-c.rst, source/includes/help-links-csharp.rst, source/includes/help-links-cxx.rst, source/includes/help-links-general.rst, source/includes/help-links-go.rst, source/includes/help-links-java.rst, source/includes/help-links-motor.rst, source/includes/help-links-node.rst, source/includes/help-links-php.rst, source/includes/help-links-pymongo.rst, source/includes/help-links-scala.rst, source/includes/help-links-swift.rst, source/tools/hadoop.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9382
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/docsworker/DOCSP-9382-community-forum-links/index.html
=> DOCSP-9382: remove links to google groups and stackoverflow for support

source/drivers.txt, source/drivers/rust.txt, source/includes/driver-table.rst, source/includes/help-links-rust.rst, source/includes/language-compatibility-table-rust.rst, source/includes/mongodb-compatibility-table-rust.rst
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/ecosystem/nathan/DOCSP-8172/drivers/rust.html)
[JIRA](https://jira.mongodb.org/browse/DOCSP-8172)
=> (DOCSP-8172) - adds Rust driver content

source/use-cases/client-side-field-level-encryption-guide.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9764
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/drivers/docsworker/DOCSP-9764-csfle-link/index.html
=> DOCSP-9764: fix links

source/includes/mongodb-compatibility-table-python.rst
https://jira.mongodb.org/browse/DOCSP-9813
https://docs-mongodbcom-staging.corp.mongodb.com/2212ab0/drivers/docsworker/DOCSP-9813/pymongo#compatibility
=> (DOCSP-9813) - remove feature compatibility note

source/go.txt
https://jira.mongodb.org/browse/DOCS-13569
https://docs-mongodbcom-staging.corp.mongodb.com/c04d324/drivers/docsworker/DOCS-13569/go#installation
@divjotarora
=> use gomod instead of dep

source/includes/language-compatibility-table-java.rst, source/includes/language-compatibility-table-scala.rst, source/includes/mongodb-compatibility-table-java.rst, source/includes/mongodb-compatibility-table-scala.rst
https://jira.mongodb.org/browse/DOCSP-9834
n/a
=> Java 4.0 and Scala 2.9 updates

source/csharp.txt, source/includes/help-links-csharp.rst
https://jira.mongodb.org/browse/DOCS-13576
https://docs-mongodbcom-staging.corp.mongodb.com/d1766f9/drivers/docsworker-xlarge/DOCS-13576/csharp
=> Corrects links on C# page

source/c.txt, source/csharp.txt, source/cxx.txt, source/go.txt, source/includes/atlas-connect-blurb.rst, source/includes/help-links-node.rst, source/java.txt, source/motor.txt, source/node.txt, source/perl.txt, source/php.txt, source/pymongo.txt, source/reactive-streams.txt, source/rust.txt, source/scala.txt, source/swift.txt
N/A
https://docs-mongodbcom-staging.corp.mongodb.com/81466a5/drivers/docsworker-xlarge/link-check/
=> corrects links and uses common atlas include

conf.py, source/scala.txt
None
https://docs-mongodbcom-staging.corp.mongodb.com/457a270/drivers/docsworker/051520-scala-link-fix/scala/
=> update link to github pages to point to most recent version

source/scala.txt
None
https://docs-mongodbcom-staging.corp.mongodb.com/bf34998/drivers/docsworker/051520-scala-link-fix-2/scala/
=> fix link in scala landing page

source/includes/language-compatibility-table-swift.rst, source/includes/mongodb-compatibility-table-swift.rst, source/swift.txt
https://jira.mongodb.org/browse/DOCSP-10619
https://docs-mongodbcom-staging.corp.mongodb.com/d2fbcc0/drivers/docsworker/DOCSP-10619-swift-landing-updates/swift/
=> DOCSP-10619: update Swift landing page for 1.0

conf.py, source/pymongo.txt, source/python.txt
https://jira.mongodb.org/browse/DOCS-13677
https://docs-mongodbcom-staging.corp.mongodb.com/7514b7e/drivers/docsworker/DOCS-13677-pymongo-links/pymongo
=> DOCS-13677 pymongo links

config/sphinx_local.yaml, snooty.toml, source/community-supported-drivers.txt, source/use-cases.txt
https://jira.mongodb.org/browse/DOCSP-10857
https://docs-mongodbcom-staging.corp.mongodb.com/9b2c8d8/drivers/docsworker/061620-use-cases-toc/use-cases
=> DOCSP-10857: add TOC to use-cases page

source/go.txt, source/includes/connection-snippets/go-connection.go
https://jira.mongodb.org/browse/DOCS-13739
https://docs-mongodbcom-staging.corp.mongodb.com/499b4c7/drivers/docsworker/DOCS-13739-fix-go-connection/go/
=> Docs 13739 fix go connection

source/includes/steps-fle-create-data-encryption-key.yaml, source/use-cases/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCSP-10121
https://docs-mongodborg-staging.corp.mongodb.com/117cb8c/drivers/docsworker/DOCSP-10121-csfle-guide-fixes/
=> DOCSP-10121: CSFLE guide fixes

snooty.toml, source/motor.txt, source/use-cases.txt
https://jira.mongodb.org/browse/DOCSP-11257
https://docs-mongodborg-staging.corp.mongodb.com/921f9c9/drivers/docsworker-xlarge/DOCSP-11257-landing-page-drawers/drivers
(try navigating to and returning to Python, PHP, Use Cases, Java)
=> DOCSP-11257 landing page drawers

source/csharp.txt
https://jira.mongodb.org/browse/DOCS-13783
https://docs-mongodbcom-staging.corp.mongodb.com/7a21f20/drivers/docsworker-xlarge/cht/csharp
=> Add link to M220N courseware

source/csharp.txt
https://docs-mongodbcom-staging.corp.mongodb.com/cf9308c/drivers/docsworker-xlarge/cht2/csharp/
=> fix borked image

source/includes/atlas-connect-blurb.rst, source/includes/help-links-java.rst, source/includes/mongodb-compatibility-table-swift.rst, source/java.txt, source/reactive-streams.txt, source/scala.txt
https://jira.mongodb.org/browse/DOCSP-11590
https://docs-mongodbcom-staging.corp.mongodb.com/ad4d568/drivers/docsworker-xlarge/DOCSP-11590-update-compat-swift/swift/#mongodb-compatibility
=> DOCSP-11590 update compat swift

source/includes/mongodb-compatibility-table-rust.rst, source/includes/mongodb-compatibility-table-swift.rst
https://jira.mongodb.org/browse/DOCSP-11590
https://docs-mongodbcom-staging.corp.mongodb.com/4e8131f/drivers/docsworker-xlarge/DOCSP-11590-update-rust-compatibility/rust/#mongodb-compatibility
=> DOCSP-11590: update Rust compatibility matrix

source/php-libraries.txt
Following https://github.com/mongodb/docs-ecosystem/pull/437.
=> Add Xenus library

source/php-libraries.txt
Also updates language for linking framework integrations for other libraries.
=> Move Doctrine ODM to list of ext-mongodb projects

source/php-libraries.txt
This is based on mongodb/docs-ecosystem#463 with suggested changes applied.
=> Add Mongolid library

source/about-compatibility.txt, source/c.txt, source/csharp.txt, source/cxx.txt, source/go.txt, source/includes/about-driver-compatibility.rst, source/index.txt, source/java.txt, source/motor.txt, source/php.txt, source/pymongo.txt, source/reactive-streams.txt, source/rust.txt, source/scala.txt, source/swift.txt
https://jira.mongodb.org/browse/DOCSP-11498
[Content](https://docs-mongodbcom-staging.corp.mongodb.com/01387f4/drivers/docsworker-xlarge/DOCSP-11498-explain-compat-matrix/about-compatibility)
[Sample placement of link to content](https://docs-mongodbcom-staging.corp.mongodb.com/01387f4/drivers/docsworker-xlarge/DOCSP-11498-explain-compat-matrix/c#language-compatibility)
=> DOCSP-11498: explain compatibility matrix

source/includes/language-compatibility-table-rust.rst, source/includes/mongodb-compatibility-table-rust.rst, source/rust.txt
https://jira.mongodb.org/browse/DOCSP-12226
https://docs-mongodbcom-staging.corp.mongodb.com/b97b492/drivers/docsworker-xlarge/DOCSP-12226-update-rust-driver/rust/
=> DOCSP-12226: Rust driver version update

source/about-compatibility.txt
https://jira.mongodb.org/browse/DOCSP-12378
https://docs-mongodbcom-staging.corp.mongodb.com/363d7b9/drivers/docsworker-xlarge/DOCSP-12378-clarify-compat-table/about-compatibility
=> DOCSP-12378: add more descriptive text to clarify compatibility tables

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
https://jira.mongodb.org/browse/DOCSP-13051
https://docs-mongodbcom-staging.corp.mongodb.com/4afceca/drivers/docsworker-xlarge/DOCSP-13051/security/client-side-field-level-encryption-local-key-to-kms#specify-the-aws-kms-provider-credentials
=> FLE AWS Dotnet

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
This adds the region info back. It was incorrectly removed.
N/A
https://docs-mongodborg-staging.corp.mongodb.com/6797600/drivers/docsworker-xlarge/region-fle-fix/
=> adds required region info to data key options

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
This includes some code updates for additional options that I wasn't using previously.
https://jira.mongodb.org/browse/DOCSP-13051
https://docs-mongodbcom-staging.corp.mongodb.com/435fb8d/drivers/docsworker-xlarge/DOCSP-13051/security/client-side-field-level-encryption-local-key-to-kms
=> Docsp 13051

source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml
https://jira.mongodb.org/browse/DOCSP-13037
https://docs-mongodborg-staging.corp.mongodb.com/154d508/drivers/docsworker-xlarge/DOCSP-13037/security/client-side-field-level-encryption-local-key-to-kms#specify-the-azure-credentials
=> FLE Azure KMS dotnet

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/security/client-side-field-level-encryption-guide.txt
This PR adds the C# driver to the CSFLE guide. It still needs to be updated to include the link to the companion CSFLE project, once that is published.
https://jira.mongodb.org/browse/DOCSP-13052
https://docs-mongodborg-staging.corp.mongodb.com/2873211/drivers/docsworker-xlarge/DOCSP-13052/security/client-side-field-level-encryption-guide
=> C# additions to the CSFLE guide

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml, source/security/client-side-field-level-encryption-guide.txt
None
https://docs-mongodbcom-staging.corp.mongodb.com/7d79db5/drivers/docsworker-xlarge/test-110920/security/client-side-field-level-encryption-local-key-to-kms
=> Snooty warning and error fixes

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/security/client-side-field-level-encryption-guide.txt
Small tweaks based on feedback from driver engineer.
N/A
https://docs-mongodbcom-staging.corp.mongodb.com/1e73336/drivers/docsworker-xlarge/csharp-cleanup/security/client-side-field-level-encryption-guide
=> minor tweaks

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml
https://jira.mongodb.org/browse/DOCSP-13089
https://docs-mongodbcom-staging.corp.mongodb.com/5ee1af8/drivers/docsworker-xlarge/DOCSP-13089-csfle-substeps/security/client-side-field-level-encryption-local-key-to-kms
=> DOCSP-13089: Divide steps in CSFLE KMS guide

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml, source/includes/steps-fle-create-data-encryption-key.yaml
No JIRA
https://docs-mongodbcom-staging.corp.mongodb.com/03047dc/drivers/docsworker-xlarge/111120-build-error-fix/security/client-side-field-level-encryption-guide
https://docs-mongodbcom-staging.corp.mongodb.com/03047dc/drivers/docsworker-xlarge/111120-build-error-fix/security/client-side-field-level-encryption-local-key-to-kms
Workerpool build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5fac563b05418b8e437815ba
Unable to find all the source errors, as they seem like false positives.
=> fix build errors

source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml
https://jira.mongodb.org/browse/DOCSP-13214
https://docs-mongodbcom-staging.corp.mongodb.com/e46f36a/drivers/docsworker-xlarge/DOCSP-13214/security/client-side-field-level-encryption-local-key-to-kms
=> go gcp kms

source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml
https://jira.mongodb.org/browse/DOCSP-13213
https://docs-mongodbcom-staging.corp.mongodb.com/3fcf5d5/drivers/docsworker-xlarge/DOCSP-13213/security/client-side-field-level-encryption-local-key-to-kms
=> go azure kms

source/includes/steps-fle-configure-the-mongodb-client.yaml, source/security/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCSP-13210
https://docs-mongodbcom-staging.corp.mongodb.com/5195ff6/drivers/docsworker-xlarge/DOCSP-13210/security/client-side-field-level-encryption-guide
=> go csfle content

source/includes/language-compatibility-table-python.rst
Updating the python language compatibility table
https://jira.mongodb.org/browse/DOCS-14067
https://docs-mongodbcom-staging.corp.mongodb.com/b6019c1/drivers/docsworker-xlarge/DOCS-14067/pymongo#python-3-compatibility
=> Docs 14067

source/security/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCS-14077
https://docs-mongodbcom-staging.corp.mongodb.com/4efd9a3/drivers/docsworker-xlarge/DOCS-14077-csfle-grammar-fix/security/client-side-field-level-encryption-guide
=> DOCS-14077: grammar fix

source/csharp.txt, source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml, source/includes/steps-fle-create-data-encryption-key.yaml, source/java-drivers.txt, source/java.txt, source/php.txt, source/pymongo.txt, source/python.txt, source/security/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCSP-13797
https://docs-mongodbcom-staging.corp.mongodb.com/30c184f/drivers/docsworker-xlarge/DOCSP-13797-fix-build-errors/
Build errors related to https://jira.mongodb.org/browse/DOP-1875 are not resolved.
=> DOCSP-13797: fix build warnings and errors

source/includes/help-links-scala.rst
https://jira.mongodb.org/browse/DOCS-14093
Issue in Snooty configuration. TODO: talk with docs platform.
=> DOCS-14093: Updated Scala help link

source/scala.txt
Update Source Code link on the Scala Driver Page. 
https://jira.mongodb.org/browse/DOCS-14091
https://docs-mongodbcom-staging.corp.mongodb.com/e4e825b/drivers/docsworker-xlarge/DOCS-14091-update-repo-link/scala
=> Docs 14091 update repo link

source/reactive-streams.txt
Update The Java Reactive Streams Sourcecode Link
https://jira.mongodb.org/browse/DOCS-14092
https://docs-mongodbcom-staging.corp.mongodb.com/42c941f/drivers/docsworker-xlarge/DOCS-14092-update-java-reactive-streams-repo/reactive-streams
=> DOCS-14092 Update Java Reactive Streams Source Code Link

source/includes/language-compatibility-table-csharp.rst
https://jira.mongodb.org/browse/DOCS-14196
https://docs-mongodbcom-staging.corp.mongodb.com/ccfcbef/drivers/docsworker-xlarge/DOCS-14196-added-Net5/csharp/
=> DOCS-14196 added .Net 5

source/includes/language-compatibility-table-csharp.rst
https://jira.mongodb.org/browse/DOCS-14196
https://docs-mongodbcom-staging.corp.mongodb.com/7a3406b/drivers/docsworker-xlarge/DOCS-14196-added-Net5/csharp/
=> Docs 14196 added net5

source/includes/language-compatibility-table-csharp.rst, source/includes/language-compatibility-table-cxx.rst, source/includes/language-compatibility-table-java-rs.rst, source/includes/language-compatibility-table-java.rst, source/includes/language-compatibility-table-motor.rst, source/includes/language-compatibility-table-python.rst
https://jira.mongodb.org/browse/DOCSP-14466
https://docs-mongodbcom-staging.corp.mongodb.com/0823028/drivers/docsworker-xlarge/DOCSP-14466-reorganizedTable/
=> Docsp 14466 reorganized table

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml
https://jira.mongodb.org/browse/DOCS-14207
https://docs-mongodbcom-staging.corp.mongodb.com/2a74e44/drivers/docsworker-xlarge/DOCS-14207-codeExamples/security/client-side-field-level-encryption-local-key-to-kms/
=> clarified python code in step 4.2

source/includes/language-compatibility-table-motor.rst, source/includes/mongodb-compatibility-table-motor.rst
https://jira.mongodb.org/browse/DOCS-14254
https://docs-mongodbcom-staging.corp.mongodb.com/7ff2851/drivers/docsworker-xlarge/DOCS-14254-updateTables/motor/
=> updated Motor tables

source/csharp.txt, source/includes/language-compatibility-table-csharp.rst, source/includes/mongodb-compatibility-table-csharp.rst
Updates csharp driver to 2.12
https://jira.mongodb.org/browse/DOCSP-15007
https://docs-mongodbcom-staging.corp.mongodb.com/f75f8ae/drivers/docsworker-xlarge/DOCSP-15007/csharp/
=> DOCSP-15007: update csharp driver to 2.12

source/pymongo.txt
Recommend to install pymongo with srv option
https://jira.mongodb.org/browse/DOCS-14274
https://docs-mongodbcom-staging.corp.mongodb.com/c3f3bb7/drivers/docsworker-xlarge/DOCS-14274/pymongo
=> recommend installation with srv (pymongo)

source/reactive-streams.txt
https://jira.mongodb.org/browse/DOCS-14248
https://docs-mongodbcom-staging.corp.mongodb.com/24a2661/drivers/docsworker-xlarge/DOCS-14248-importUpdates/reactive-streams/
=> DOCS-14248 updated reactivestreams import statements

source/includes/language-compatibility-table-csharp.rst
https://jira.mongodb.org/browse/DOCSP-15673
https://docs-mongodbcom-staging.corp.mongodb.com/27f7f55/drivers/docsworker-xlarge/DOCSP-15673-CsharpAtlasNote/csharp/#compatibility
=> DOCSP-15673 added note about .Net5 and MongoDB 4.0

source/includes/mongodb-compatibility-table-go.rst
https://jira.mongodb.org/browse/DOCSP-15077
https://docs-mongodbcom-staging.corp.mongodb.com/a2ccb97/drivers/docsworker-xlarge/DOCSP-15077-go-1.5/go/
=> DOCSP-15077: update tables for Go driver v1.5

source/includes/language-compatibility-table-python.rst, source/includes/mongodb-compatibility-table-python.rst
Renamed "Python Driver" as "Pymongo Driver Version"
https://jira.mongodb.org/browse/DOCSP-15089
https://docs-mongodbcom-staging.corp.mongodb.com/d63834f/drivers/docsworker-xlarge/DOCSP-15089-pymongo-clarification/pymongo/
=> DOCSP-15089 pymongo clarification

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-azure.yaml, source/includes/steps-fle-convert-to-a-remote-master-key-gcp.yaml, source/security/client-side-field-level-encryption-guide.txt
https://jira.mongodb.org/browse/DOCSP-15726
11 tables:
https://docs-mongodbcom-staging.corp.mongodb.com/c22df90/drivers/docsworker-xlarge/DOCSP-15726-ColumnWidths/security/client-side-field-level-encryption-guide/
6 tables:
https://docs-mongodbcom-staging.corp.mongodb.com/c22df90/drivers/docsworker-xlarge/DOCSP-15726-ColumnWidths/security/client-side-field-level-encryption-local-key-to-kms/
=> DOCSP-15726 fixed column widths

source/csharp.txt
https://jira.mongodb.org/browse/DOCSP-16034
https://docs-mongodbcom-staging.corp.mongodb.com/0bb926d/drivers/docsworker-xlarge/DOCSP-16034-csharp-vs-compat/csharp/
=> DOCSP-16034 csharp vs compat

source/includes/university-m220p.rst, source/motor.txt, source/pymongo.txt, source/python.txt
https://jira.mongodb.org/browse/DOCSP-16255
https://docs-mongodbcom-staging.corp.mongodb.com/615a6b7/drivers/docsworker-xlarge/DOCSP-16255-python-updates/python/
https://docs-mongodbcom-staging.corp.mongodb.com/615a6b7/drivers/docsworker-xlarge/DOCSP-16255-python-updates/pymongo/
https://docs-mongodbcom-staging.corp.mongodb.com/615a6b7/drivers/docsworker-xlarge/DOCSP-16255-python-updates/motor/
=> DOCSP-16255 python updates

source/c.txt, source/csharp.txt, source/cxx.txt, source/go.txt, source/includes/localhost-connection.rst, source/motor.txt, source/php.txt, source/pymongo.txt, source/reactive-streams.txt, source/rust.txt, source/scala.txt, source/swift.txt
Added a note about connecting to localhost on the following pages: 
- C Driver
- C++ Driver
- C# Driver
- Go Driver
- Java Reactive Streams Driver
- PHP Driver
- PyMongo Driver
- Motor Driver
- Scala Driver
- Swift Driver
- Rust Driver 
https://jira.mongodb.org/browse/DOCSP-16447
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-16447-LocalhostConnection/
=> DOCSP-16447 localhost connection

source/c.txt, source/csharp.txt, source/go.txt, source/includes/versioned-api-blurb.rst
https://jira.mongodb.org/browse/DOCSP-17096
Changes only made for Go at the moment
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17096-versioned-api-ex/go/
=> DOCSP-17096: versioned api ex

config/redirects, source/java-drivers.txt
This simplifies navigation to the new java driver.
https://jira.mongodb.org/browse/DOCSP-15578
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-15578/java-drivers/
=> Docsp 15578

source/c.txt, source/csharp.txt, source/cxx.txt, source/go.txt, source/includes/localhost-connection.rst, source/motor.txt, source/php.txt, source/pymongo.txt, source/reactive-streams.txt, source/rust.txt, source/scala.txt, source/swift.txt
Would especially appreciate feedback on whether there's a better way to format the section.
https://jira.mongodb.org/browse/DOCSP-17383
[C Driver](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17383-localhost-connection/c/#connect-to-a-mongodb-server-on-your-local-machine)
[C++ Driver](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17383-localhost-connection/cxx/#connect-to-a-mongodb-server-on-your-local-machine)
[C# Driver](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17383-localhost-connection/csharp/#connect-to-a-mongodb-server-on-your-local-machine)
[Go Driver](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17383-localhost-connection/go/#connect-to- …
=> DOCSP-17383 localhost connection

snooty.toml, source/csharp.txt
https://jira.mongodb.org/browse/DOCSP-17960
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-17960-csharp-links/csharp/
=> DOCSP-17960: update csharp docs links to latest version

source/community-supported-drivers.txt
https://jira.mongodb.org/browse/DOCSP-18121
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-18121-old-comm-drivers/community-supported-drivers/
=> DOCSP-18121: removed stale community drivers

source/includes/language-compatibility-table-motor.rst, source/includes/mongodb-compatibility-table-motor.rst
https://jira.mongodb.org/browse/DOCS-14768
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612e6c917dcf01293072bfab
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-14768/motor/#mongodb-compatibility
=> update motor compat tables

config/redirects, source/index.txt
=> Redirect go to new docset

config/redirects
https://jira.mongodb.org/browse/DOCSP-NNNNN
**Paste your workerpool job link here**
https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/NNNNN/index.html
=> try absolute path

.github/pull_request_template.md, source/php-libraries.txt
https://jira.mongodb.org/browse/DOCSP-18843
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=615200c58670bd273107df67
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-18843-fixlinks/php-libraries/
=> DOCSP-18843 fix links

source/includes/language-compatibility-table-php.rst, source/includes/php-mongodb-compatibility-table.rst
https://jira.mongodb.org/browse/DOCSP-19384
Untested.
Untested.
=> Update PHP compatibility tables

source/includes/language-compatibility-table-python.rst, source/includes/mongodb-compatibility-table-python.rst
Updating python info
https://jira.mongodb.org/browse/DOCSP-19903
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61a66d015314b0809f2cfc6c
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19903/pymongo/#compatibility
=> update compat for pymongo

source/community-supported-drivers.txt
https://jira.mongodb.org/browse/DOCS-14972
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61aff90b5314b0809f54a398
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-14972/community-supported-drivers/
=> add deno_mongo to community page

snooty.toml, source/includes/mongodb-compatibility-table-php.rst, source/includes/steps-fle-convert-to-a-remote-master-key-kmip.yaml, source/security/client-side-field-level-encryption-local-key-to-kms.txt
Document KMIP Support
https://jira.mongodb.org/browse/DOCSP-19240
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61bb8a40c52f2a460f2e7853
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19240-Support-KMIP/security/client-side-field-level-encryption-local-key-to-kms/
=> (DOCSP-19240) CSFLE KMIP Java

source/community-supported-drivers.txt, source/php-libraries.txt
This removes outdated community resources, and corrects the link to the mandango project in the PHP page.
N/A
https://jira.mongodb.org/browse/DOCSP-20476
[**Paste your workerpool job link here**](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62190f1f9c4c7f6bfb7943c0)
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/community-sweep/php-libraries/#stand-alone-libraries-1
=> Community sweep

source/includes/steps-fle-convert-to-a-remote-master-key-aws.yaml, source/security/client-side-field-level-encryption-local-key-to-kms.txt
Add coverage of IAM Role support for authentication with AWS in CSFLE.
https://jira.mongodb.org/browse/DOCSP-19842
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=622bb02a0ab54725f1904c76
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-19842-CSFLE-IAM-Role/security/client-side-field-level-encryption-local-key-to-kms/#create-an-aws-iam-user
=> (DOCSP-19842) CSFLE IAM Role

snooty.toml, source/driver-compatibility-reference.txt, source/includes/driver-table.rst, source/includes/localhost-connection.rst, source/includes/mongodb-compatibility-table-c.rst, source/includes/mongodb-compatibility-table-php.rst, source/includes/steps-fle-create-data-encryption-key.yaml, source/index.txt, source/java-drivers.txt, source/java.txt, source/php.txt
This prepared the docs-ecosystem repo for the new domain.
https://jira.mongodb.org/browse/DOCSP-20369
[**Paste your workerpool job link here**
](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=623a4c1a0ab54725f158cbc9)
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-20369/
=> subdomain changes

source/csharp.txt
https://jira.mongodb.org/browse/DOCSP-20273
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=625702350fdfea9c37be7efb
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-20273/csharp/
=> link to analyer

snooty.toml, source/includes/help-links-java.rst, source/includes/help-links-scala.rst, source/includes/steps-fle-create-data-encryption-key.yaml, source/reactive-streams.txt, source/scala.txt, source/security/client-side-field-level-encryption-guide.txt
This updates `snooty.toml` with new constants and uses those constants for linking to the scale and reactive-streams driver.
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=625d74d30fdfea9c37fd7215)
[JIRA](https://jira.mongodb.org/browse/DOCSP-20862)
[Reactive Streams Page](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-20862/reactive-streams/)
[Scala Page](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-20862/scala/)
=> Docsp 20862

.github/pull_request_template.md, README.rst
Updates to README and PR template
=> ecosystem public changes

source/includes/mongodb-compatibility-table-swift.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-22462>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-22462-swift-v1.3-compat-update/swift/>
=> DOCSP-22462: swift v1.3 compatibility updates

source/php.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/061322-typo-fix/php/#mongodb-compatibility
=> 061322 fix php typo

source/includes/language-compatibility-table-python.rst, source/includes/mongodb-compatibility-table-python.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-23095>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-23905/pymongo/#compatibility>
=> remove beta tag

source/pymongo.txt
JIRA - <https://jira.mongodb.org/browse/DOCS-15747>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-15747-update-pymongo-installation/pymongo/#installation>
=> DOCS-15747 Update PyMongo Installation Instructions 

source/includes/language-compatibility-table-php.rst, source/includes/mongodb-compatibility-table-php.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-26681>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-26681-php-version-updates-1.15/php/>
=> DOCSP-26681 PHP library version update

source/csharp.txt
JIRA - https://jira.mongodb.org/browse/DOCS-15758
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/docs-15758-mdbu-csharp/csharp/
=> DOCS-15758 - C# MDBU link

source/reactive-streams.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25436
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-25436/reactive-streams/
=> DOCSP-25436 Added a note about synchronous Java drivers.

source/includes/university-m220p.rst
Staging - [<https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/link-fixes/python/)
=> update links to M220P 

config/redirects, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27439
=> DOCSP-27439 C# link

snooty.toml, source/csharp.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/csharp-banner/csharp/
=> Add banner for c# docs

source/c.txt, source/cxx.txt, source/includes/connection-snippets/scram/c-connection-no-stable-api.c, source/includes/connection-snippets/scram/c-connection.c, source/includes/connection-snippets/scram/cxx-connection-no-stable-api.cpp, source/includes/connection-snippets/scram/cxx-connection.cpp
JIRA - <https://jira.mongodb.org/browse/DOCSP-28246>
Staging:
- [C](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-28246-stable-api-updates/c/#connect-to-mongodb-atlas)
- [C++](https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-28246-stable-api-updates/cxx/#connect-to-mongodb-atlas)
=> DOCSP-28246 stable api updates

snooty.toml, source/index.txt, source/typescript.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-26722>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-26722/typescript/>
=> Docsp 26722: Adding TypeScript landing page

source/index.txt
JIRA - [DOP-3375](https://jira.mongodb.org/browse/DOP-3375)
Staging - https://docs-mongodbcom-integration.corp.mongodb.com/5bb2e3da94e6e3f79fab7b5be9c1928b474786ea/feature/DOP-3375/drivers/caesarbell/feature/DOP-3375/
=> :tada: adds new cards and value along with additional section in the txt file

source/pymongo.txt
JIRA - <https://jira.mongodb.org/browse/DOCS-15877>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCS-15877-pymongo-lambda/pymongo/#connect-to-mongodb-atlas-from-aws-lambda
=> DOCS-15877: Add AWS Lambda link to PyMongo landing page

snooty.toml, source/index.txt, source/ruby.txt
JIRA - [DOCSP-30020](https://jira.mongodb.org/browse/DOCSP-30020)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-30020-ruby-landingpg/ruby/ and see left-side nav
=> DOCSP-30020: Ruby landing page

source/php-libraries.txt
For review by the docs team:
Reverts mongodb/docs-ecosystem#889
=> Revert "PHPORM-26: Remove legacy projects"

source/facets.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-32483>
Hey @mongoKart - here's the facet.toml file for the Drivers ecosystem repo.  Please merge if everything's ok!
Thanks!
Sarah
=> DOCSP-32483 programmatic tagging script for ecosystem repo

source/includes/fact-environments.rst, source/java-drivers.txt, source/php.txt, source/pymongo.txt
**JIRA**
https://jira.mongodb.org/browse/DOCSP-32301
https://jira.mongodb.org/browse/DOCSP-32302
https://jira.mongodb.org/browse/DOCSP-32299
**Staging**
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-32301/java-drivers/
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-32301/pymongo/
https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-32301/php/
**Build**
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650d8bd0492df295cfcf7806
=> (DOCSP-32301)(DOCSP-32302)(DOCSP-32299) Adds compatibility info to top drivers pages

source/python.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32875>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-32875-pymongoarrow/python/
=> DOCSP-32875: add PyMongoArrow

source/kotlin-drivers.txt
Note: This is an attempted deployment fix, recommended by the docs platform team.
JIRA - <https://jira.mongodb.org/browse/DOCSP-26721>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-26721-add-kotlin-sdk-link/kotlin-drivers/
=> DOCSP-26721 add kotlin sdk link

source/kotlin-drivers.txt
This is an attempt to resolve a reported (to #ask-docs-platform), but currently unresolved issue with the deployment of this repo. The issue surfaced after merging https://github.com/mongodb/docs-ecosystem/pull/917/files which rendered correctly on staging.
The attempted fix was made in https://github.com/mongodb/docs-ecosystem/pull/918/files, which also worked on staging, but the deploy did not succeed.
This update removes the last directive in the original PR in an attempt to fix the deployment.
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/100923-test-realm-directive/kotlin-drivers/
=> test link without realm directive

source/includes/connection-snippets/scram/py-motor-connection-no-stableapi.py, source/includes/connection-snippets/scram/py-motor-connection-tornado.py, source/includes/connection-snippets/scram/py-motor-connection.py
JIRA - https://jira.mongodb.org/browse/DOCSP-33659
Staging - https://preview-mongodbmongokart.gatsbyjs.io/drivers/docsp-33659-use-await/motor/
=> DOCSP-33659 - add await

.github/pull_request_template.md, source/motor.txt
=> 110823: Taxonomy tagging and PR template update

source/motor.txt
=> add programming language and keyword

source/php.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35793>
Staging:
- [Landing page](https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/DOCSP-35793-add-laravel-to-left-nav/)
=> DOCSP-35793: add Laravel MongoDB to left nav

config/redirects, snooty.toml, source/includes/help-links-php.rst, source/index.txt, source/php-drivers.txt
Description:
Reverts the changes made in [this PR](https://github.com/mongodb/docs-ecosystem/pull/939)
JIRA - None
Staging - [PHP Driver](https://preview-mongodbcchomongodb.gatsbyjs.io/drivers/012424-revert-DOCSP-35623/php-drivers/)
=> 012424: Revert DOCSP-35623

source/documentdb-support.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37440>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/drivers/DOCSP-37440-index-documentdb/documentdb-support/
=> DOCSP-37440: documentdb feedback on indexes

source/python-drivers.txt
JIRA - N/A
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/drivers/pymongoarrow-link/python-drivers/
- [N/A] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
=> Link to new PyMongoArrow docs

source/cxx.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/cxx-landing-page-links/cxx/>
=> Update landings page links

config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-36132>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-36132-pt2/>
=> [C++] Update C++ Docs URL slug from cxx to cpp - pt 2

config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-38481
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/drivers/DOCSP-38481-add-redirect/
=> DOCSP-38481: Add C redirect

source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39062
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/drivers/DOCSP-39062-update-lang-pills/
=> DOCSP-39062: Link to language landing pages

source/python-drivers.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39415>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-39415-add-docs-to-left-navbar/python-drivers/>
=> DOCSP-39415 added pymongoarrow link to toc

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-40728>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/drivers/DOCSP-40728-5.1.1-patch/kotlin-sync/
=> DOCSP-40728: v5.1.1 updates for kotlin sync

source/about-compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41514>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/drivers/DOCSP-41514-compat-about-note/about-compatibility/
=> DOCSP-41514: compat table note

source/includes/stable-api-snippets/kotlin-sync-client.kt, source/kotlin-sync.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40639>
Staging - <https://preview-mongodbstephmarie17.gatsbyjs.io/drivers/docsp-40639-fixInstallInstructions/kotlin-sync/>
=> DOCSP-40639 Fix Kotlin Sync import statements

source/swift.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42385>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/drivers/DOCSP-42303-placeholders/swift/>
=> DOCSP-42303: Update username/password placeholders

config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
- [N/A] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
=> Add redirect for old compat reference page

source/php-drivers.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44610>
Staging -
=> DOCSP-44610: fix php links

source/includes/language-compatibility-table-php.rst, source/includes/mongodb-compatibility-table-php.rst, source/php-drivers.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50063
Staging - https://deploy-preview-1008--docs-ecosystem.netlify.app/php-drivers/#compatibility
=> DOCSP-50063: Add missing PHP compat tables
